<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-BFMJ2UG" failures="1" tests="4" name="Test" time="14.343" errors="0" timestamp="2024-10-15T15:07:08 IST">
  <testcase classname="api.test.UserTestcase" name="validateCreateUser" time="4.216"/>
  <testcase classname="api.test.UserTestcase" name="validateGetUser" time="2.859"/>
  <testcase classname="api.test.UserTestcase" name="validateUpdateUser" time="3.982"/>
  <testcase classname="api.test.UserTestcase" name="validateDeleteUser" time="1.439">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTestcase.validateDeleteUser(UserTestcase.java:113)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- validateDeleteUser -->
</testsuite> <!-- Test -->
